# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import profile_pb2 as profile__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="history.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rhistory.proto\x1a\rprofile.proto"A\n\x07History\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1c\n\x05teams\x18\x03 \x03(\x0e\x32\r.Profile.Team"\x1c\n\x0eHistoryRequest\x12\n\n\x02id\x18\x01 \x01(\x05"/\n\x0fHistoryResponse\x12\x1c\n\x05teams\x18\x03 \x03(\x0e\x32\r.Profile.Team2:\n\x0eHistoryService\x12(\n\x03Get\x12\x0f.HistoryRequest\x1a\x10.HistoryResponseb\x06proto3',
    dependencies=[
        profile__pb2.DESCRIPTOR,
    ],
)


_HISTORY = _descriptor.Descriptor(
    name="History",
    full_name="History",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="History.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="History.name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="teams",
            full_name="History.teams",
            index=2,
            number=3,
            type=14,
            cpp_type=8,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=32,
    serialized_end=97,
)


_HISTORYREQUEST = _descriptor.Descriptor(
    name="HistoryRequest",
    full_name="HistoryRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="HistoryRequest.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=99,
    serialized_end=127,
)


_HISTORYRESPONSE = _descriptor.Descriptor(
    name="HistoryResponse",
    full_name="HistoryResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="teams",
            full_name="HistoryResponse.teams",
            index=0,
            number=3,
            type=14,
            cpp_type=8,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=129,
    serialized_end=176,
)

_HISTORY.fields_by_name["teams"].enum_type = profile__pb2._PROFILE_TEAM
_HISTORYRESPONSE.fields_by_name["teams"].enum_type = profile__pb2._PROFILE_TEAM
DESCRIPTOR.message_types_by_name["History"] = _HISTORY
DESCRIPTOR.message_types_by_name["HistoryRequest"] = _HISTORYREQUEST
DESCRIPTOR.message_types_by_name["HistoryResponse"] = _HISTORYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

History = _reflection.GeneratedProtocolMessageType(
    "History",
    (_message.Message,),
    {
        "DESCRIPTOR": _HISTORY,
        "__module__": "history_pb2"
        # @@protoc_insertion_point(class_scope:History)
    },
)
_sym_db.RegisterMessage(History)

HistoryRequest = _reflection.GeneratedProtocolMessageType(
    "HistoryRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _HISTORYREQUEST,
        "__module__": "history_pb2"
        # @@protoc_insertion_point(class_scope:HistoryRequest)
    },
)
_sym_db.RegisterMessage(HistoryRequest)

HistoryResponse = _reflection.GeneratedProtocolMessageType(
    "HistoryResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _HISTORYRESPONSE,
        "__module__": "history_pb2"
        # @@protoc_insertion_point(class_scope:HistoryResponse)
    },
)
_sym_db.RegisterMessage(HistoryResponse)


_HISTORYSERVICE = _descriptor.ServiceDescriptor(
    name="HistoryService",
    full_name="HistoryService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=178,
    serialized_end=236,
    methods=[
        _descriptor.MethodDescriptor(
            name="Get",
            full_name="HistoryService.Get",
            index=0,
            containing_service=None,
            input_type=_HISTORYREQUEST,
            output_type=_HISTORYRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_HISTORYSERVICE)

DESCRIPTOR.services_by_name["HistoryService"] = _HISTORYSERVICE

# @@protoc_insertion_point(module_scope)
