# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="profile.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rprofile.proto"\xfe\x02\n\x07Profile\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x04team\x18\x03 \x01(\x0e\x32\r.Profile.Team\x12\x1b\n\x04role\x18\x04 \x01(\x0e\x32\r.Profile.Role\x12"\n\x08\x63hannels\x18\x05 \x03(\x0e\x32\x10.Profile.Channel\x12$\n\rpreviousTeams\x18\x06 \x03(\x0e\x32\r.Profile.Team"S\n\x04Role\x12\x11\n\rPRODUCT_OWNER\x10\x00\x12\x0c\n\x08\x45NGINEER\x10\x01\x12\x0c\n\x08\x44\x45SIGNER\x10\x02\x12\x0e\n\nQA_MANAGER\x10\x03\x12\x0c\n\x08OPERATOR\x10\x04"5\n\x04Team\x12\t\n\x05\x41PPLE\x10\x00\x12\n\n\x06\x42\x41NANA\x10\x01\x12\n\n\x06\x43HERRY\x10\x02\x12\n\n\x06\x44URIAN\x10\x03"I\n\x07\x43hannel\x12\x0f\n\x0b\x44\x45VELOPMENT\x10\x00\x12\x13\n\x0fTODAY_I_LEARNED\x10\x01\x12\n\n\x06OFFICE\x10\x02\x12\x0c\n\x08HAVE_FUN\x10\x03"\x07\n\x05\x45mpty"\x1e\n\x0eProfileRequest\x12\x0c\n\x04name\x18\x01 \x01(\t" \n\x0e\x43reateResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08"*\n\x0cListProfiles\x12\x1a\n\x08profiles\x18\x01 \x03(\x0b\x32\x08.Profile2~\n\x0eProfileService\x12#\n\x06\x43reate\x12\x08.Profile\x1a\x0f.CreateResponse\x12%\n\x03Get\x12\x0f.ProfileRequest\x1a\r.ListProfiles\x12 \n\x07GetList\x12\x06.Empty\x1a\r.ListProfilesb\x06proto3',
)


_PROFILE_ROLE = _descriptor.EnumDescriptor(
    name="Role",
    full_name="Profile.Role",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="PRODUCT_OWNER",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="ENGINEER",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="DESIGNER",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="QA_MANAGER",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="OPERATOR",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=187,
    serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_PROFILE_ROLE)

_PROFILE_TEAM = _descriptor.EnumDescriptor(
    name="Team",
    full_name="Profile.Team",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="APPLE",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="BANANA",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="CHERRY",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="DURIAN",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=272,
    serialized_end=325,
)
_sym_db.RegisterEnumDescriptor(_PROFILE_TEAM)

_PROFILE_CHANNEL = _descriptor.EnumDescriptor(
    name="Channel",
    full_name="Profile.Channel",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="DEVELOPMENT",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="TODAY_I_LEARNED",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="OFFICE",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="HAVE_FUN",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=327,
    serialized_end=400,
)
_sym_db.RegisterEnumDescriptor(_PROFILE_CHANNEL)


_PROFILE = _descriptor.Descriptor(
    name="Profile",
    full_name="Profile",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="Profile.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="Profile.name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="team",
            full_name="Profile.team",
            index=2,
            number=3,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="role",
            full_name="Profile.role",
            index=3,
            number=4,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="channels",
            full_name="Profile.channels",
            index=4,
            number=5,
            type=14,
            cpp_type=8,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="previousTeams",
            full_name="Profile.previousTeams",
            index=5,
            number=6,
            type=14,
            cpp_type=8,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _PROFILE_ROLE,
        _PROFILE_TEAM,
        _PROFILE_CHANNEL,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=18,
    serialized_end=400,
)


_EMPTY = _descriptor.Descriptor(
    name="Empty",
    full_name="Empty",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=402,
    serialized_end=409,
)


_PROFILEREQUEST = _descriptor.Descriptor(
    name="ProfileRequest",
    full_name="ProfileRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="ProfileRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=411,
    serialized_end=441,
)


_CREATERESPONSE = _descriptor.Descriptor(
    name="CreateResponse",
    full_name="CreateResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="CreateResponse.status",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=443,
    serialized_end=475,
)


_LISTPROFILES = _descriptor.Descriptor(
    name="ListProfiles",
    full_name="ListProfiles",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="profiles",
            full_name="ListProfiles.profiles",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=477,
    serialized_end=519,
)

_PROFILE.fields_by_name["team"].enum_type = _PROFILE_TEAM
_PROFILE.fields_by_name["role"].enum_type = _PROFILE_ROLE
_PROFILE.fields_by_name["channels"].enum_type = _PROFILE_CHANNEL
_PROFILE.fields_by_name["previousTeams"].enum_type = _PROFILE_TEAM
_PROFILE_ROLE.containing_type = _PROFILE
_PROFILE_TEAM.containing_type = _PROFILE
_PROFILE_CHANNEL.containing_type = _PROFILE
_LISTPROFILES.fields_by_name["profiles"].message_type = _PROFILE
DESCRIPTOR.message_types_by_name["Profile"] = _PROFILE
DESCRIPTOR.message_types_by_name["Empty"] = _EMPTY
DESCRIPTOR.message_types_by_name["ProfileRequest"] = _PROFILEREQUEST
DESCRIPTOR.message_types_by_name["CreateResponse"] = _CREATERESPONSE
DESCRIPTOR.message_types_by_name["ListProfiles"] = _LISTPROFILES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Profile = _reflection.GeneratedProtocolMessageType(
    "Profile",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROFILE,
        "__module__": "profile_pb2"
        # @@protoc_insertion_point(class_scope:Profile)
    },
)
_sym_db.RegisterMessage(Profile)

Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "profile_pb2"
        # @@protoc_insertion_point(class_scope:Empty)
    },
)
_sym_db.RegisterMessage(Empty)

ProfileRequest = _reflection.GeneratedProtocolMessageType(
    "ProfileRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROFILEREQUEST,
        "__module__": "profile_pb2"
        # @@protoc_insertion_point(class_scope:ProfileRequest)
    },
)
_sym_db.RegisterMessage(ProfileRequest)

CreateResponse = _reflection.GeneratedProtocolMessageType(
    "CreateResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _CREATERESPONSE,
        "__module__": "profile_pb2"
        # @@protoc_insertion_point(class_scope:CreateResponse)
    },
)
_sym_db.RegisterMessage(CreateResponse)

ListProfiles = _reflection.GeneratedProtocolMessageType(
    "ListProfiles",
    (_message.Message,),
    {
        "DESCRIPTOR": _LISTPROFILES,
        "__module__": "profile_pb2"
        # @@protoc_insertion_point(class_scope:ListProfiles)
    },
)
_sym_db.RegisterMessage(ListProfiles)


_PROFILESERVICE = _descriptor.ServiceDescriptor(
    name="ProfileService",
    full_name="ProfileService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=521,
    serialized_end=647,
    methods=[
        _descriptor.MethodDescriptor(
            name="Create",
            full_name="ProfileService.Create",
            index=0,
            containing_service=None,
            input_type=_PROFILE,
            output_type=_CREATERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Get",
            full_name="ProfileService.Get",
            index=1,
            containing_service=None,
            input_type=_PROFILEREQUEST,
            output_type=_LISTPROFILES,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetList",
            full_name="ProfileService.GetList",
            index=2,
            containing_service=None,
            input_type=_EMPTY,
            output_type=_LISTPROFILES,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_PROFILESERVICE)

DESCRIPTOR.services_by_name["ProfileService"] = _PROFILESERVICE

# @@protoc_insertion_point(module_scope)
